dua3.keystoremanager.main.title=Keystore Manager
dua3.keystoremanager.main.copyright=©2025 Axel Howind
dua3.keystoremanager.main.description=A simple Keystore Management Tool.
dua3.keystoremanager.manager.error.title=Application Error
dua3.keystoremanager.manager.error.header=An application error occurred. Please report this error to the developer.
dua3.keystoremanager.manager.menu.view=View
dua3.keystoremanager.manager.menu.view.appearance=Appearance
dua3.keystoremanager.manager.menu.tools=Tools
dua3.keystoremanager.manager.menu.tools.validate_pem=Validate PEM?
dua3.keystoremanager.manager.title=Keystore Manager
dua3.keystoremanager.manager.error.content_changed_precondition=Setting content to empty is only allowed for the last tab
dua3.keystoremanager.pane.empty_name=Add Keystore
dua3.keystoremanager.pane.error.creating_private_key=Error creating private key
dua3.keystoremanager.pane.error.creating_public_key=Error creating public key
dua3.keystoremanager.pane.error.copy_to_clipboard=Failed to copy to clipboard.
dua3.keystoremanager.pane.error.opening_keystore=Error opening keystore
dua3.keystoremanager.pane.error.saving_keystore=Error saving KeyStore
dua3.keystoremanager.pane.error.saving_keystore.header=The keystore could not be saved.
dua3.keystoremanager.pane.info.keystore_saved.title=Keystore saved
dua3.keystoremanager.pane.info.keystore_saved.header=The keystore has been successfully saved.
dua3.keystoremanager.pane.info.keystore_exported_clipboard.title=Keystore exported to Clipboard
dua3.keystoremanager.pane.info.keystore_exported_clipboard.header=The keystore has been converted to BASE64 and copied to the clipboard.
dua3.keystoremanager.pane.error.exporting_keystore.title=Error exporting keystore
dua3.keystoremanager.pane.error.exporting_keystore.header=An error occurred while exporting the keystore.
dua3.keystoremanager.pane.error.key_generation_failed=Key generation failed.
dua3.keystoremanager.pane.error.certificate_validation_failed=Certificate validation failed.
dua3.keystoremanager.pane.button.create_keystore=Create new Keystore
dua3.keystoremanager.pane.button.load_keystore=Open existing Keystore
dua3.keystoremanager.pane.label.keystore_type=Keystore Type
dua3.keystoremanager.pane.label.keystore_path=Keystore Path
dua3.keystoremanager.pane.label.entries=Entries
dua3.keystoremanager.pane.table.column.alias=Alias
dua3.keystoremanager.pane.table.column.type=Type
dua3.keystoremanager.pane.table.column.creation_date=Creation Date
dua3.keystoremanager.pane.menu.copy_alias=Copy Alias
dua3.keystoremanager.pane.menu.export=Export?
dua3.keystoremanager.pane.menu.save=Save
dua3.keystoremanager.pane.menu.save_as=Save as?
dua3.keystoremanager.pane.menu.add=Add
dua3.keystoremanager.pane.menu.add.private_key=Private Key?
dua3.keystoremanager.pane.menu.add.secret_key=Secret Key?
dua3.keystoremanager.pane.dialog.create_keystore.title=Create Keystore
dua3.keystoremanager.pane.dialog.open_keystore.title=Open Keystore
dua3.keystoremanager.pane.dialog.save_keystore.title=Save Keystore
dua3.keystoremanager.pane.dialog.export.title=Export
dua3.keystoremanager.pane.dialog.new_private_key.title=New Private Key
dua3.keystoremanager.pane.dialog.new_secret_key.title=New Secret Key
dua3.keystoremanager.pane.dialog.new_secret_key.header=New Secret Key
dua3.keystoremanager.pane.filter.keystore_files=Keystore files
dua3.keystoremanager.pane.filter.p12=PKS#12 Keystore files
dua3.keystoremanager.pane.filter.jks=JKS Keystore files
dua3.keystoremanager.pane.filter.jceks=JCEKS Keystore files
dua3.keystoremanager.pane.filter.all_files=All files
dua3.keystoremanager.dialog.create_keystore.title=Create Keystore
dua3.keystoremanager.dialog.create_keystore.folder=Folder
dua3.keystoremanager.dialog.create_keystore.folder.select=Select an existing folder
dua3.keystoremanager.dialog.create_keystore.name=Name
dua3.keystoremanager.dialog.create_keystore.name.required=Name is required
dua3.keystoremanager.dialog.create_keystore.type=Type
dua3.keystoremanager.dialog.create_keystore.password=Password
dua3.keystoremanager.dialog.create_keystore.password.repeat=Repeat Password
dua3.keystoremanager.dialog.details.title=Keystore Entry Details
dua3.keystoremanager.dialog.details.private_key_details=Private Key Details
dua3.keystoremanager.dialog.details.certificate=Certificate
dua3.keystoremanager.dialog.details.type=Type
dua3.keystoremanager.dialog.details.algorithm=Algorithm
dua3.keystoremanager.dialog.details.key_size=Key Size
dua3.keystoremanager.dialog.details.key_size.format={0} bits
dua3.keystoremanager.dialog.details.valid_from=Valid From
dua3.keystoremanager.dialog.details.valid_until=Valid Until
dua3.keystoremanager.dialog.details.subject_fields=Subject fields
dua3.keystoremanager.dialog.details.public_key=Public Key
dua3.keystoremanager.dialog.details.private_key=Private Key
dua3.keystoremanager.dialog.details.show_private_key=Show Private Key
dua3.keystoremanager.dialog.details.hide_private_key=Hide Private Key
dua3.keystoremanager.dialog.details.unlock_private_key.title=Unlock Private Key
dua3.keystoremanager.dialog.details.unlock_private_key.header=Enter the password to unlock the private key.
dua3.keystoremanager.dialog.details.unlock_private_key.password=Password
dua3.keystoremanager.dialog.details.show_secret_key=Show Secret Key
dua3.keystoremanager.dialog.details.hide_secret_key=Hide Secret Key
dua3.keystoremanager.dialog.details.unlock_secret_key.title=Unlock Secret Key
dua3.keystoremanager.dialog.details.unlock_secret_key.header=Enter the password to unlock the secret key.
dua3.keystoremanager.dialog.details.unlock_secret_key.password=Password
dua3.keystoremanager.dialog.details.certificate_chain=Certificate Chain
dua3.keystoremanager.dialog.details.certificate_chain.format=Subject: {0}\nIssuer: {1}\nValid: {2} .. {3}
dua3.keystoremanager.dialog.details.certificate_chain.other_type={0} certificate
dua3.keystoremanager.dialog.details.certificate_chain.none=No certificate chain available.
dua3.keystoremanager.dialog.details.error.access_denied=Access Denied
dua3.keystoremanager.dialog.details.error.unlock_failed=Could not unlock private key
dua3.keystoremanager.dialog.details.error.unlock_secret_failed=Could not unlock secret key
dua3.keystoremanager.dialog.details.error.retrieve_private_failed=Could not retrieve private key.
dua3.keystoremanager.dialog.details.error.not_a_private_key=The entry with alias ''{0}'' is not a private key.
dua3.keystoremanager.dialog.details.error.check_password=Check if the password is correct: {0}
dua3.keystoremanager.dialog.details.error.retrieve_secret_failed=Could not retrieve secret key.
dua3.keystoremanager.dialog.details.error.not_a_secret_key=The entry with alias ''{0}'' is not a secret key.
dua3.keystoremanager.dialog.details.error=Error
dua3.keystoremanager.dialog.details.trusted_cert_details=Trusted Certificate Details
dua3.keystoremanager.dialog.details.unknown_entry_details=Unknown Entry Details
dua3.keystoremanager.dialog.details.alias=Alias
dua3.keystoremanager.dialog.details.hidden=[hidden]
dua3.keystoremanager.dialog.details.unknown=unknown
dua3.keystoremanager.dialog.details.unsupported_entry_type=Unsupported entry type: {0}
dua3.keystoremanager.pane.type.unknown=Unknown
dua3.keystoremanager.pane.type.key_entry=Key Entry
dua3.keystoremanager.pane.type.trusted_cert=Trusted Certificate
dua3.keystoremanager.pane.type.secret_key=Secret Key
dua3.keystoremanager.pane.type.private_key=Private Key
dua3.keystoremanager.pane.type.format.with_algorithm={0} ({1})
dua3.keystoremanager.pane.type.format.with_size={0} ({1} bits)
dua3.keystoremanager.pane.type.format.with_algorithm_and_size={0} ({1}, {2} bits)
